### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kidonng** [kidonng/kidonng.me#1]
## Functions

- [x] Livere comment
- [x] Lightbox
- [x] Serif/Sans Serif font family switch
- [x] Highlight
- [x] Generate anchor for headings
- [x] Updated date info
- [x] Link to source document

## Packages

- Add `kidonng` package (packages/kidonng)
- Remove `saber-plugin-baidu-analytics` (packages/saber-plugin-baidu-analytics)
- Remove `saber-plugin-baidu-push` (packages/saber-plugin-baidu-push)
- Remove `normalize.css`
- Remove `intersection-observer`
- Add `smoothscroll-for-websites`

## Fork

- `vue-headroom`
- `lozad`

## Theme

- Header: Add click to scroll to top (packages/saber-theme-aimer/src/components/Header.vue)
- Footer: Remove social network icons (packages/saber-theme-aimer/src/components/Footer.vue)
- Default: (packages/saber-theme-aimer/src/layouts/default.vue)
  - Add auto navigate to anchor
  - Remove Disqus component
  - `scroll-behavior: smooth`
- Home: (packages/saber-theme-aimer/src/layouts/home.vue)
  - Add title for avatar
  - Remove location text
  - Change author name font
- Config: (packages/saber-theme-aimer/src/saber-browser.js)
  - Remove black footer class
  - Remove fake Hexo meta
  - Remove icon font
- Base style: Hide overflow-x (for transition) (packages/saber-theme-aimer/src/styles/components/_base.scss)
- Add transition (packages/saber-theme-aimer/src/styles/components/_transitions.scss)
- Dark mode for 404 page
